/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: rubykamen (https://sketchfab.com/rubykamen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/blackhole-74cbeaeae2174a218fe9455d77902b5c
Title: Blackhole
*/

import { a } from "@react-spring/three";
import { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";




import blackHoleScene from "../assets/3d/blackhole.glb";

const BlackHole = ({
    isRotating,
    setIsRotating,
    setCurrentStage,
    currentFocusPoint,
    ...props
}) => {

  const blackHoleRef = useRef();
  // Get access to the Three.js renderer and viewport
  const { gl, viewport } = useThree();
  const { nodes, materials, animations } = useGLTF(blackHoleScene);
  const { actions } = useAnimations(animations, blackHoleRef);

    
  // Use a ref for the last mouse x position
  const lastX = useRef(0);
  // Use a ref for rotation speed
  const rotationSpeed = useRef(0);
  // Define a damping factor to control rotation damping
  const dampingFactor = 0.95;


  // // Handle pointer (mouse or touch) down event
  // const handlePointerDown = (event) => {
  //   event.stopPropagation();
  //   // event.preventDefault();
  //   setIsRotating(true);

  //   // Calculate the clientX based on whether it's a touch event or a mouse event
  //   const clientX = event.touches ? event.touches[0].clientX : event.clientX;

  //   // Store the current clientX position for reference
  //   lastX.current = clientX;
  // };

  // // Handle pointer (mouse or touch) up event
  // const handlePointerUp = (event) => {
  //   event.stopPropagation();
  //   // event.preventDefault();
  //   setIsRotating(false);
  // };

  // // Handle pointer (mouse or touch) move event
  // const handlePointerMove = (event) => {
  //   event.stopPropagation();
  //   // event.preventDefault();
  //   if (isRotating) {
  //     // If rotation is enabled, calculate the change in clientX position
  //     const clientX = event.touches ? event.touches[0].clientX : event.clientX;

  //     // calculate the change in the horizontal position of the mouse cursor or touch input,
  //     // relative to the viewport's width
  //     const delta = (clientX - lastX.current) / viewport.width;

  //     // Update the black hole's rotation based on the mouse/touch movement
  //     blackHoleRef.current.rotation.y += delta * 0.01 * Math.PI;

  //     // Update the reference for the last clientX position
  //     lastX.current = clientX;

  //     // Update the rotation speed
  //     rotationSpeed.current = delta * 0.01 * Math.PI;
  //   }
  // };

  // Handle keydown events
  const handleKeyDown = (event) => {
    if (event.key === "ArrowRight" || event.key === "ArrowDown") {
      if (!isRotating) setIsRotating(true);

      blackHoleRef.current.rotation.y += 0.009 * Math.PI;
      rotationSpeed.current = 0.09;
    } else if (event.key === "ArrowLeft" || event.key === "ArrowUp") {
      if (!isRotating) setIsRotating(true);

      blackHoleRef.current.rotation.y -= 0.009 * Math.PI;
      rotationSpeed.current = -0.09;
    }
  };

  // Handle keyup events
  const handleKeyUp = (event) => {
    if (event.key === "ArrowLeft" || event.key === "ArrowRight" || event.key === "ArrowUp" || event.key === "ArrowDown") {
      setIsRotating(false);
    }
  };

  // Ref to store the timeout ID
  const rotationEndTimeoutRef = useRef();

  // Handle scroll event
  const handleScrollDown = (event) => {
    event.stopPropagation();
    setIsRotating(true);

    // Determine the scroll delta
    const scrollDelta = event.deltaY;

    // Adjust the factor based on the desired sensitivity
    const rotationChange = scrollDelta * 0.0001 * Math.PI;

    // Update the black hole's rotation
    blackHoleRef.current.rotation.y += rotationChange;

    // Update the rotation speed
    rotationSpeed.current = rotationChange;

    // Clear any existing timeout
    clearTimeout(rotationEndTimeoutRef.current);

    // Set a new timeout
    rotationEndTimeoutRef.current = setTimeout(() => {
      setIsRotating(false);
    }, 100); // Adjust the timeout duration as needed
  };



  useEffect(() => {
    actions['Take 001'].play();
  }, [])
  
  useEffect(() => {
    // Add event listeners for pointer and keyboard events
    const blackHole = blackHoleRef.current;
    if (blackHole) {
      // blackHole.addEventListener("pointerdown", handlePointerDown);
      // blackHole.addEventListener("pointerup", handlePointerUp);
      // blackHole.addEventListener("pointermove", handlePointerMove);
      window.addEventListener("keydown", handleKeyDown);
      window.addEventListener("keyup", handleKeyUp);
      window.addEventListener("wheel", handleScrollDown);
    }

    // Remove event listeners when component unmounts
    return () => {
      if (blackHole) {
        // blackHole.removeEventListener("pointerdown", handlePointerDown);
        // blackHole.removeEventListener("pointerup", handlePointerUp);
        // blackHole.removeEventListener("pointermove", handlePointerMove);
        window.removeEventListener("keydown", handleKeyDown);
        window.removeEventListener("keyup", handleKeyUp);
        window.removeEventListener("wheel", handleScrollDown);
      }
    };
  }, [gl, handleScrollDown]);

  // This function is called on each frame update
  useFrame(() => {
    // If not rotating, apply damping to slow down the rotation (smoothly)
    if (!isRotating) {
      // Apply damping factor
      rotationSpeed.current *= dampingFactor;

      // Stop rotation when speed is very small
      if (Math.abs(rotationSpeed.current) < 0.001) {
        rotationSpeed.current = 0;
      }

      blackHoleRef.current.rotation.y += rotationSpeed.current;
    } else {
      // When rotating, determine the current stage based on black hole's orientation
      const rotation = blackHoleRef.current.rotation.y;

      const normalizedRotation =
        ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);

      // Set the current stage based on the black hole's orientation
      const degreeToRadian = degree => degree * Math.PI / 180;
      const stageRange = degreeToRadian(80);
      const gapRange = degreeToRadian(10);

      const stage1Start = 0;
      const stage2Start = stage1Start + stageRange + gapRange;
      const stage3Start = stage2Start + stageRange + gapRange;
      const stage4Start = stage3Start + stageRange + gapRange;
      
      // Update the switch statement
      switch (true) {
        case normalizedRotation >= stage1Start && normalizedRotation < stage1Start + stageRange:
          setCurrentStage(1);
          break;
        case normalizedRotation >= stage2Start && normalizedRotation < stage2Start + stageRange:
          setCurrentStage(2);
          break;
        case normalizedRotation >= stage3Start && normalizedRotation < stage3Start + stageRange:
          setCurrentStage(3);
          break;
        case normalizedRotation >= stage4Start && normalizedRotation < stage4Start + stageRange:
          setCurrentStage(4);
          break;
        default:
          setCurrentStage(null);
      }           
    }
  });
  
  return (
    <group 
      ref={blackHoleRef}
      {...props} 
      dispose={null}
      // onPointerDown={handlePointerDown}
      // onPointerUp={handlePointerUp}
      // onPointerMove={handlePointerMove}
      onScroll={handleScrollDown}
    >
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.016}
        >
          <group
            name="415c209837844e7b91255101a7c3eb67fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Blackhole_core"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={0.968}
                >
                  <mesh
                    name="Blackhole_core_Blackhole_core_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Blackhole_core_Blackhole_core_0.geometry}
                    material={materials.Blackhole_core}
                  />
                </group>
                <group name="Blackhole_ring" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh
                    name="Blackhole_ring_Blackhole_ring_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Blackhole_ring_Blackhole_ring_0.geometry}
                    material={materials.Blackhole_ring}
                  />
                </group>
                <group
                  name="Blackhole_skin_001"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={0.959}
                >
                  <mesh
                    name="Blackhole_skin_001_Blackhole_skin_0"
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.Blackhole_skin_001_Blackhole_skin_0.geometry
                    }
                    material={materials.Blackhole_skin}
                  />
                </group>
                <group
                  name="Blackhole_skin_002"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={0.957}
                >
                  <mesh
                    name="Blackhole_skin_002_Blackhole_core_0"
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.Blackhole_skin_002_Blackhole_core_0.geometry
                    }
                    material={materials.Blackhole_core}
                  />
                </group>
                <group
                  name="Blackhole_skin_003"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={0.91}
                >
                  <mesh
                    name="Blackhole_skin_003_Blackhole_skin_0"
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.Blackhole_skin_003_Blackhole_skin_0.geometry
                    }
                    material={materials.Blackhole_skin}
                  />
                </group>
                <group
                  name="Blackhole_skin_004"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={0.908}
                >
                  <mesh
                    name="Blackhole_skin_004_Blackhole_core_0"
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.Blackhole_skin_004_Blackhole_core_0.geometry
                    }
                    material={materials.Blackhole_core}
                  />
                </group>
                <group
                  name="Blackhole_skin_005"
                  rotation={[-Math.PI / 2, 0, 0.96]}
                  scale={0.9}
                >
                  <mesh
                    name="Blackhole_skin_005_Blackhole_skin_0"
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.Blackhole_skin_005_Blackhole_skin_0.geometry
                    }
                    material={materials.Blackhole_skin}
                  />
                </group>
                <group
                  name="Blackhole_skin_006"
                  rotation={[-Math.PI / 2, 0, -2.007]}
                  scale={0.864}
                >
                  <mesh
                    name="Blackhole_skin_006_Blackhole_skin_inner_0"
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.Blackhole_skin_006_Blackhole_skin_inner_0.geometry
                    }
                    material={materials.Blackhole_skin_inner}
                  />
                </group>
                <group
                  name="Blackhole_skin_007"
                  rotation={[-Math.PI / 2, 0, -2.007]}
                  scale={0.866}
                >
                  <mesh
                    name="Blackhole_skin_007_Blackhole_core_0"
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.Blackhole_skin_007_Blackhole_core_0.geometry
                    }
                    material={materials.Blackhole_core}
                  />
                </group>
                <group name="Blackhole_core001" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh
                    name="Blackhole_core001_Blackhole_core_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Blackhole_core001_Blackhole_core_0.geometry}
                    material={materials.Blackhole_core}
                  />
                </group>
                <group
                  name="Blackhole_skin_008"
                  rotation={[-Math.PI / 2, 0, 0.087]}
                  scale={0.845}
                >
                  <mesh
                    name="Blackhole_skin_008_Blackhole_skin_inner_0"
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.Blackhole_skin_008_Blackhole_skin_inner_0.geometry
                    }
                    material={materials.Blackhole_skin_inner}
                  />
                </group>
                <group
                  name="Blackhole_skin_009"
                  rotation={[-Math.PI / 2, 0, -0.611]}
                  scale={0.887}
                >
                  <mesh
                    name="Blackhole_skin_009_Blackhole_skin_0"
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.Blackhole_skin_009_Blackhole_skin_0.geometry
                    }
                    material={materials.Blackhole_skin}
                  />
                </group>
                <group
                  name="Blackhole_skin_010"
                  rotation={[-Math.PI / 2, 0, -2.531]}
                  scale={0.929}
                >
                  <mesh
                    name="Blackhole_skin_010_Blackhole_skin_0"
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.Blackhole_skin_010_Blackhole_skin_0.geometry
                    }
                    material={materials.Blackhole_skin}
                  />
                </group>
                <group
                  name="Blackhole_skin_011"
                  rotation={[-Math.PI / 2, 0, -2.531]}
                  scale={0.928}
                >
                  <mesh
                    name="Blackhole_skin_011_Blackhole_core_0"
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.Blackhole_skin_011_Blackhole_core_0.geometry
                    }
                    material={materials.Blackhole_core}
                  />
                </group>
                <group
                  name="Blackhole_skin_012"
                  rotation={[-Math.PI / 2, 0, 2.094]}
                  scale={0.856}
                >
                  <mesh
                    name="Blackhole_skin_012_Blackhole_skin_inner_0"
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.Blackhole_skin_012_Blackhole_skin_inner_0.geometry
                    }
                    material={materials.Blackhole_skin_inner}
                  />
                </group>
                <group
                  name="Blackhole_skin_013"
                  rotation={[-Math.PI / 2, 0, -2.967]}
                  scale={0.835}
                >
                  <mesh
                    name="Blackhole_skin_013_Blackhole_ring2_0"
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.Blackhole_skin_013_Blackhole_ring2_0.geometry
                    }
                    material={materials.Blackhole_ring2}
                  />
                </group>
                <group
                  name="Blackhole_core002"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={0.928}
                >
                  <mesh
                    name="Blackhole_core002_Blackhole_ring2_0"
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.Blackhole_core002_Blackhole_ring2_0.geometry
                    }
                    material={materials.Blackhole_ring2}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

export default BlackHole;


